stages:
  - test
  - build
  - deploy

run_nginx_tests:
  stage: test
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  variables:
    TEST_HTTP_URL: "http://docker:8080"
    TEST_HTTPS_URL: "https://docker:8443"
  before_script:
    - mkdir -p certs
    - apk add --no-cache openssl
    - openssl req -x509 -nodes -days 1 -newkey rsa:2048 -keyout certs/privkey.pem -out certs/fullchain.pem -subj "/CN=localhost"
    - docker-compose -f docker-compose.test.yml up -d --build
    - sleep 15
  script:
    - docker-compose -f docker-compose.test.yml exec -T backend npm install
    - docker-compose -f docker-compose.test.yml exec -T backend npm run test
  after_script:
    - docker-compose -f docker-compose.test.yml down

build_app:
  stage: build

production_deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
    - eval $(ssh-agent -s)
    - echo '$SSH-PRIVATE-KEY' | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $SERVER-HOST >> ~/.ssh/known_hosts
  script:
    - ssh $SERVER_USER@$SERVER_HOST "
      cd /var/www/strun-vibration &&
      git pull origin main &&
      npm install --production &&
      sudo systemctl restart strun-vibration.service
      nginx -s reload
      "
  only:
   - main
  when: manual
